# Name of the workflow
name: Automate CV Update

# Event - What starts this workflow?
on:
    workflow_dispatch:
    repository_dispatch:
      types: [google-sheet-update]
    schedule:
      - cron: '30 * * * *'  
    
# Jobs - What the computer should do? 
jobs:
    render-rmd:
        runs-on: ubuntu-latest

        steps:
         - uses: actions/checkout@v3
         - uses: r-lib/actions/setup-pandoc@v2
         - uses: r-lib/actions/setup-r@v2
         - name: install packages
           uses: r-lib/actions/setup-r-dependencies@v2
           with:
            packages: |
              any::rmarkdown
              any::pagedown
              any::magrittr
              any::googlesheets4
              any::tidyverse
         - uses: browser-actions/setup-chrome@v1
         - name: render rmd to get html
           run: |
            Rscript -e 'rmarkdown::render("cv.rmd")'
         - name: convert html to pdf
           run: |
            Rscript -e 'pagedown::chrome_print("cv.html")'
         - name: config github
           run: |
            git config --local user.name "$GITHUB_ACTOR"
            git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
         - name: commit and push updates
           run: |
            git add .
            git commit -m "Update CV" || echo "No changes to commit"
            git push origin || echo "No changes to commit"