name: Update CV

on: 
  workflow_dispatch:
  repository_dispatch:
    types: [google-sheet-update]

jobs:
  render-rmarkdown:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: set up pandoc
        uses: r-lib/actions/setup-pandoc@v2
      
      - name: Set up R environment
        uses: r-lib/actions/setup-r@v2
      
      - name: Install R dependencies
        run: |
          Rscript -e "install.packages('rmarkdown', 'pagedown', 'magrittr')"
      
      - name: Render CV from RMarkdown
        run: |
          Rscript -e "rmarkdown::render('cv.rmd')"
      
      - name: Configure Git
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "melodysyue@gmail.com"
      
      - name: Commit and Push updates
        run: |
          git add cv.pdf cv.html
          git commit -m "Update CV" || echo "No changes to commit"
          git push
