name: Update CV

on: 
  workflow_dispatch:
  repository_dispatch:
    types: [google-sheet-update]

jobs:
  render-rmarkdown:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
            fetch-depth: 0
    
      - uses: r-lib/actions/setup-pandoc@v2
    
      - uses: r-lib/actions/setup-r@v2
          
      - name: Render rmd files and Commit Results
        run: |
          rmarkdown::render('cv.rmd')
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "melodysyue@gmail.com"
          git add cv.pdf cv.html
          git commit -m "Update CV"
          git push
