name: testing out the github actions

on: 
    push: 
        branches: ["main"]

jobs:
    testing:
        runs-on: ubuntu-latest
        steps:
            - run: |
                echo "This works!"