# Event - What starts this workflow?
on:
    workflow_dispatch:
  
  # Name of the workflow
name: hello-r-world
  
  # Jobs - What the computer should do? 
jobs:
    write-message:
        # Use Ubuntu   
        runs-on: macOS-latest
        steps:
         - uses: actions/checkout@v3
         - uses: r-lib/actions/setup-pandoc@v2
         - uses: r-lib/actions/setup-r@v2
         - name: install packages
           run: |
            Rscript -e 'install.packages(c("rmarkdown", "pagedown", "magrittr", "googlesheets4", "tidyverse"))'
         - name: render rmd
           run: |
            Rscript -e 'rmarkdown::render("cv.rmd")'
         - name: config github
           run: |
            git config --local user.name "$GITHUB_ACTOR"
            git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
         - name: Commit and Push updates
           run: |
            git add cv.pdf cv.html
            git commit -m "Update CV"
            git push
         - name: print-message
           run: |
            Rscript -e 'print("It runs succesfully!")' 