# Name of the workflow
name: CV Update

# Event - What starts this workflow?
on:
    workflow_dispatch:
    repository_dispatch:
      types: [google-sheet-update]  
    
# Jobs - What the computer should do? 
jobs:
    render-rmd:
        runs-on: macOS-latest

        steps:
         - uses: actions/checkout@v3
         - uses: r-lib/actions/setup-pandoc@v2
         - uses: r-lib/actions/setup-r@v2
         - name: install packages
           run: |
            Rscript -e 'install.packages(c("rmarkdown", "pagedown", "magrittr", "googlesheets4", "tidyverse"))'
         - name: install Google Chrome
           run: |
            sudo apt-get update
            sudo apt-get install -y google-chrome-stable
         - name: render rmd to get html
           run: |
            Rscript -e 'rmarkdown::render("cv.rmd")'
         - name: knit rmd to get pdf
           run: |
            Rscript -e 'rmarkdown::knit("cv.rmd")'
         - name: config github
           run: |
            git config --local user.name "$GITHUB_ACTOR"
            git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
         - name: commit and push updates
           run: |
            git add .
            git commit -m "Update CV" || echo "No changes to commit"
            git push origin || echo "No changes to commit"